image:
  pullPolicy: Always
  repository: wallarm-dkr-support.jfrog.io/wallarm-support-bot
  tag: 0.1.2
  pullSecrets:
  - regcred  
mysql: 
  mysqlDatabase: wallarm_support_bot
  mysqlUser: bot
  mysqlPassword: ""
  persistence: 
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi
  resources: {}

botTelegramConfig:
  APItoken: ""
logLevel: info
sleepBeforeTerm: 10
resources: {}
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 2
readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 1
  failureThreshold: 2
