apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wallarm-support-bot.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  user: {{ .Values.mysql.mysqlUser | b64enc | quote }} 
  password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  token: {{ .Values.botTelegramConfig.APItoken | b64enc | quote }}

